version: 2.1

workflows:
  test-deploy:
    jobs:
      - test  # This should be a string referring to the job name

jobs:
  test:
    docker:
      - image: cimg/node:23.5.0
    steps:
      - checkout
      - run: 
          name: Install Dependency
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
